# Generated by Django 5.1.5 on 2025-01-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
