# Generated by Django 5.1.5 on 2025-01-29 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to="fin_app.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transfer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer",
                to="fin_app.transfer",
            ),
        ),
    ]
