# Generated by Django 5.1.5 on 2025-01-29 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_app", "0003_alter_transaction_account_alter_transaction_transfer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="fin_app.account",
            ),
        ),
    ]
