# Generated by Django 5.1.5 on 2025-01-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin_app", "0004_alter_transaction_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="cancel_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
